services:
  - type: web
    name: django-blog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true  # Render will create a secure key
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db  # Must match your DB name
          property: connectionString
      - key: DEBUG
        value: "False"