services:
  - type: web
    name: django-blog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "venv/bin/gunicorn blog_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"
    disk:
      name: media_storage
      mountPath: /opt/render/project/src/media/
      sizeGB: 1
    routes:
      - type: rewrite
        source: /media/*
        destination: /media/$1